# Generated by Django 4.0.4 on 2022-05-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc_p', models.FloatField()),
                ('hsc_p', models.FloatField()),
                ('degree_p', models.FloatField()),
                ('workex', models.IntegerField()),
                ('etest_p', models.FloatField()),
                ('specialisation', models.IntegerField()),
            ],
        ),
    ]
